//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.DeleteBoilerplate;

[assembly: RegisterDocumentType(BasePage.CLASS_NAME, typeof(BasePage))]

namespace CMS.DocumentEngine.Types.DeleteBoilerplate
{
	/// <summary>
	/// Represents a content item of type BasePage.
	/// </summary>
	public partial class BasePage : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "DeleteBoilerplate.BasePage";


		/// <summary>
		/// The instance of the class that provides extended API for working with BasePage fields.
		/// </summary>
		private readonly BasePageFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// BasePageID.
		/// </summary>
		[DatabaseIDField]
		public int BasePageID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("BasePageID"), 0);
			}
			set
			{
				SetValue("BasePageID", value);
			}
		}


		/// <summary>
		/// Base Page Field.
		/// </summary>
		[DatabaseField]
		public string BasePageField
		{
			get
			{
				return ValidationHelper.GetString(GetValue("BasePageField"), @"");
			}
			set
			{
				SetValue("BasePageField", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with BasePage fields.
		/// </summary>
		[RegisterProperty]
		public BasePageFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with BasePage fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class BasePageFields : AbstractHierarchicalObject<BasePageFields>
		{
			/// <summary>
			/// The content item of type BasePage that is a target of the extended API.
			/// </summary>
			private readonly BasePage mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="BasePageFields" /> class with the specified content item of type BasePage.
			/// </summary>
			/// <param name="instance">The content item of type BasePage that is a target of the extended API.</param>
			public BasePageFields(BasePage instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// BasePageID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.BasePageID;
				}
				set
				{
					mInstance.BasePageID = value;
				}
			}


			/// <summary>
			/// Base Page Field.
			/// </summary>
			public string Field
			{
				get
				{
					return mInstance.BasePageField;
				}
				set
				{
					mInstance.BasePageField = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="BasePage" /> class.
		/// </summary>
		public BasePage() : base(CLASS_NAME)
		{
			mFields = new BasePageFields(this);
		}

		#endregion
	}
}