//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.DeleteBoilerplate;

[assembly: RegisterDocumentType(SocialLinkSection.CLASS_NAME, typeof(SocialLinkSection))]

namespace CMS.DocumentEngine.Types.DeleteBoilerplate
{
    /// <summary>
    /// Represents a content item of type SocialLinkSection.
    /// </summary>
    public partial class SocialLinkSection : TreeNode
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "DeleteBoilerplate.SocialLinkSection";


        /// <summary>
        /// The instance of the class that provides extended API for working with SocialLinkSection fields.
        /// </summary>
        private readonly SocialLinkSectionFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// Gets an object that provides extended API for working with SocialLinkSection fields.
        /// </summary>
        [RegisterProperty]
        public SocialLinkSectionFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with SocialLinkSection fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class SocialLinkSectionFields : AbstractHierarchicalObject<SocialLinkSectionFields>
        {
            /// <summary>
            /// The content item of type SocialLinkSection that is a target of the extended API.
            /// </summary>
            private readonly SocialLinkSection mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="SocialLinkSectionFields" /> class with the specified content item of type SocialLinkSection.
            /// </summary>
            /// <param name="instance">The content item of type SocialLinkSection that is a target of the extended API.</param>
            public SocialLinkSectionFields(SocialLinkSection instance)
            {
                mInstance = instance;
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="SocialLinkSection" /> class.
        /// </summary>
        public SocialLinkSection() : base(CLASS_NAME)
        {
            mFields = new SocialLinkSectionFields(this);
        }

        #endregion
    }
}