//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.DeleteBoilerplate;

[assembly: RegisterDocumentType(NewsPage.CLASS_NAME, typeof(NewsPage))]

namespace CMS.DocumentEngine.Types.DeleteBoilerplate
{
	/// <summary>
	/// Represents a content item of type NewsPage.
	/// </summary>
	public partial class NewsPage : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "DeleteBoilerplate.NewsPage";


		/// <summary>
		/// The instance of the class that provides extended API for working with NewsPage fields.
		/// </summary>
		private readonly NewsPageFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// NewsPageID.
		/// </summary>
		[DatabaseIDField]
		public int NewsPageID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("NewsPageID"), 0);
			}
			set
			{
				SetValue("NewsPageID", value);
			}
		}


		/// <summary>
		/// TitleNews.
		/// </summary>
		[DatabaseField]
		public string TitleNews
		{
			get
			{
				return ValidationHelper.GetString(GetValue("TitleNews"), @"");
			}
			set
			{
				SetValue("TitleNews", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with NewsPage fields.
		/// </summary>
		[RegisterProperty]
		public NewsPageFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with NewsPage fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class NewsPageFields : AbstractHierarchicalObject<NewsPageFields>
		{
			/// <summary>
			/// The content item of type NewsPage that is a target of the extended API.
			/// </summary>
			private readonly NewsPage mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="NewsPageFields" /> class with the specified content item of type NewsPage.
			/// </summary>
			/// <param name="instance">The content item of type NewsPage that is a target of the extended API.</param>
			public NewsPageFields(NewsPage instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// NewsPageID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.NewsPageID;
				}
				set
				{
					mInstance.NewsPageID = value;
				}
			}


			/// <summary>
			/// TitleNews.
			/// </summary>
			public string TitleNews
			{
				get
				{
					return mInstance.TitleNews;
				}
				set
				{
					mInstance.TitleNews = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="NewsPage" /> class.
		/// </summary>
		public NewsPage() : base(CLASS_NAME)
		{
			mFields = new NewsPageFields(this);
		}

		#endregion
	}
}