//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.DeleteBoilerplate;

[assembly: RegisterDocumentType(Blog.CLASS_NAME, typeof(Blog))]

namespace CMS.DocumentEngine.Types.DeleteBoilerplate
{
	/// <summary>
	/// Represents a content item of type Blog.
	/// </summary>
	public partial class Blog : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "DeleteBoilerplate.Blog";


		/// <summary>
		/// The instance of the class that provides extended API for working with Blog fields.
		/// </summary>
		private readonly BlogFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// NewsPageID.
		/// </summary>
		[DatabaseIDField]
		public int NewsPageID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("NewsPageID"), 0);
			}
			set
			{
				SetValue("NewsPageID", value);
			}
		}


		/// <summary>
		/// Base Page Field.
		/// </summary>
		[DatabaseField]
		public string BasePageField
		{
			get
			{
				return ValidationHelper.GetString(GetValue("BasePageField"), @"");
			}
			set
			{
				SetValue("BasePageField", value);
			}
		}


		/// <summary>
		/// Name.
		/// </summary>
		[DatabaseField]
		public string Name
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Name"), @"");
			}
			set
			{
				SetValue("Name", value);
			}
		}


		/// <summary>
		/// Title.
		/// </summary>
		[DatabaseField]
		public string Title
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Title"), @"");
			}
			set
			{
				SetValue("Title", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with Blog fields.
		/// </summary>
		[RegisterProperty]
		public BlogFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with Blog fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class BlogFields : AbstractHierarchicalObject<BlogFields>
		{
			/// <summary>
			/// The content item of type Blog that is a target of the extended API.
			/// </summary>
			private readonly Blog mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="BlogFields" /> class with the specified content item of type Blog.
			/// </summary>
			/// <param name="instance">The content item of type Blog that is a target of the extended API.</param>
			public BlogFields(Blog instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// NewsPageID.
			/// </summary>
			public int NewsPageID
			{
				get
				{
					return mInstance.NewsPageID;
				}
				set
				{
					mInstance.NewsPageID = value;
				}
			}


			/// <summary>
			/// Base Page Field.
			/// </summary>
			public string BasePageField
			{
				get
				{
					return mInstance.BasePageField;
				}
				set
				{
					mInstance.BasePageField = value;
				}
			}


			/// <summary>
			/// Name.
			/// </summary>
			public string Name
			{
				get
				{
					return mInstance.Name;
				}
				set
				{
					mInstance.Name = value;
				}
			}


			/// <summary>
			/// Title.
			/// </summary>
			public string Title
			{
				get
				{
					return mInstance.Title;
				}
				set
				{
					mInstance.Title = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="Blog" /> class.
		/// </summary>
		public Blog() : base(CLASS_NAME)
		{
			mFields = new BlogFields(this);
		}

		#endregion
	}
}